version: '2'
services:
  web:
    environment:
      PEPIS_CMS_DATABASE_CONFIG_TYPE: native
      PEPIS_CMS_DATABASE_HOSTNAME: db
      PEPIS_CMS_DATABASE_USERNAME: pepiscms
      PEPIS_CMS_DATABASE_PASSWORD: pepiscms
      PEPIS_CMS_DATABASE_DATABASE: pepiscms
      PEPIS_CMS_AUTH_DRIVER: native
      PEPIS_CMS_AUTH_EMAIL: demo@example.com
      PEPIS_CMS_AUTH_PASSWORD: demodemo
      PEPIS_CMS_SITE_EMAIL: demo@example.com
      PEPIS_CMS_SITE_NAME: Demonstration
      PEPIS_CMS_OBJECT_CACHE_OBJECT_IS_ENABLED: 'true'
      PEPIS_CMS_IS_UNATTENDED_INSTALL: 'true'
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./tmp/html:/var/www/html # Uncomment this line if you want to preview/edit files
#      - /home/${USER}/.ssh/id_rsa:/root/.ssh/id_rsa # Uncomment if you need to pull any custom composer packages
      - ./pepiscms:/var/www/html/vendor/piotrpolak/pepiscms/pepiscms
      - ./features:/var/www/html/vendor/piotrpolak/pepiscms/features
      - ./docs:/var/www/html/vendor/piotrpolak/pepiscms/docs
      - ./behat.yml:/var/www/html/vendor/piotrpolak/pepiscms/behat.yml
      - ./composer.json:/var/www/html/vendor/piotrpolak/pepiscms/composer.json
      - ./tests:/var/www/html/vendor/piotrpolak/pepiscms/tests
      - ./phpunit.xml.dist:/var/www/html/vendor/piotrpolak/pepiscms/phpunit.xml.dist
      - ./CHANGELOG.md:/var/www/html/vendor/piotrpolak/pepiscms/CHANGELOG.md
      - ./install.php:/var/www/html/vendor/piotrpolak/pepiscms/install.php
      - ./composer.json:/var/www/html/untouchable/composer.json:ro
      - ./.php_cs.dist:/var/www/html/.php_cs.dist
      - ./tmp/.composer/:/root/.composer/
    build: ./build/docker/web/
    command: /install.sh

  db:
    image: mariadb:10.5
    restart: always
# Uncomment this to persist MySQL data between concurrent runs
#    volumes:
#      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pepiscms
      MYSQL_PASSWORD: pepiscms
      MYSQL_DATABASE: pepiscms
#    ports:
#      - "3306:3306"