var extensions = {
    '3gp': 'file_extension_3gp.png',
    '7z': 'file_extension_7z.png',
    'ace': 'file_extension_ace.png',
    'ai': 'file_extension_ai.png',
    'aif': 'file_extension_aif.png',
    'aiff': 'file_extension_aiff.png',
    'amr': 'file_extension_amr.png',
    'asf': 'file_extension_asf.png',
    'asx': 'file_extension_asx.png',
    'bat': 'file_extension_bat.png',
    'bin': 'file_extension_bin.png',
    'bmp': 'file_extension_bmp.png',
    'bup': 'file_extension_bup.png',
    'cab': 'file_extension_cab.png',
    'cbr': 'file_extension_cbr.png',
    'cda': 'file_extension_cda.png',
    'cdl': 'file_extension_cdl.png',
    'cdr': 'file_extension_cdr.png',
    'chm': 'file_extension_chm.png',
    'dat': 'file_extension_dat.png',
    'divx': 'file_extension_divx.png',
    'dll': 'file_extension_dll.png',
    'dmg': 'file_extension_dmg.png',
    'doc': 'file_extension_doc.png',
    'dss': 'file_extension_dss.png',
    'dvf': 'file_extension_dvf.png',
    'dwg': 'file_extension_dwg.png',
    'eml': 'file_extension_eml.png',
    'eps': 'file_extension_eps.png',
    'exe': 'file_extension_exe.png',
    'fla': 'file_extension_fla.png',
    'flv': 'file_extension_flv.png',
    'gif': 'file_extension_gif.png',
    'gz': 'file_extension_gz.png',
    'hqx': 'file_extension_hqx.png',
    'htm': 'file_extension_htm.png',
    'html': 'file_extension_html.png',
    'ifo': 'file_extension_ifo.png',
    'indd': 'file_extension_indd.png',
    'iso': 'file_extension_iso.png',
    'jar': 'file_extension_jar.png',
    'jpeg': 'file_extension_jpeg.png',
    'jpg': 'file_extension_jpg.png',
    'lnk': 'file_extension_lnk.png',
    'log': 'file_extension_log.png',
    'm4a': 'file_extension_m4a.png',
    'm4b': 'file_extension_m4b.png',
    'm4p': 'file_extension_m4p.png',
    'm4v': 'file_extension_m4v.png',
    'mcd': 'file_extension_mcd.png',
    'mdb': 'file_extension_mdb.png',
    'mid': 'file_extension_mid.png',
    'mov': 'file_extension_mov.png',
    'mp2': 'file_extension_mp2.png',
    'mp4': 'file_extension_mp4.png',
    'mpeg': 'file_extension_mpeg.png',
    'mpg': 'file_extension_mpg.png',
    'msi': 'file_extension_msi.png',
    'mswmm': 'file_extension_mswmm.png',
    'ogg': 'file_extension_ogg.png',
    'pdf': 'file_extension_pdf.png',
    'png': 'file_extension_png.png',
    'pps': 'file_extension_pps.png',
    'ps': 'file_extension_ps.png',
    'psd': 'file_extension_psd.png',
    'pst': 'file_extension_pst.png',
    'ptb': 'file_extension_ptb.png',
    'pub': 'file_extension_pub.png',
    'qbb': 'file_extension_qbb.png',
    'qbw': 'file_extension_qbw.png',
    'qxd': 'file_extension_qxd.png',
    'ram': 'file_extension_ram.png',
    'rar': 'file_extension_rar.png',
    'rm': 'file_extension_rm.png',
    'rmvb': 'file_extension_rmvb.png',
    'rtf': 'file_extension_rtf.png',
    'sea': 'file_extension_sea.png',
    'ses': 'file_extension_ses.png',
    'sit': 'file_extension_sit.png',
    'sitx': 'file_extension_sitx.png',
    'ss': 'file_extension_ss.png',
    'swf': 'file_extension_swf.png',
    'tgz': 'file_extension_tgz.png',
    'thm': 'file_extension_thm.png',
    'tif': 'file_extension_tif.png',
    'tmp': 'file_extension_tmp.png',
    'torrent': 'file_extension_torrent.png',
    'ttf': 'file_extension_ttf.png',
    'txt': 'file_extension_txt.png',
    'vcd': 'file_extension_vcd.png',
    'vob': 'file_extension_vob.png',
    'wav': 'file_extension_wav.png',
    'wma': 'file_extension_wma.png',
    'wmv': 'file_extension_wmv.png',
    'wps': 'file_extension_wps.png',
    'xls': 'file_extension_xls.png',
    'xpi': 'file_extension_xpi.png',
    'zip': 'file_extension_zip.png'
};

function getFileIcon(ext) {
    if (extensions[ext]) {
        return extensions[ext];
    }
    return 'file_extension_dat.png';
}

function getFileExtension(path) {
    var last_index = path.lastIndexOf('.');
    if (path.length == -1) {
        return "";
    }
    path = path.substr(last_index + 1).toLowerCase();

    return path;
}
