SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS cms_remote_applications;
DROP TABLE IF EXISTS cms_site_languages;
DROP TABLE IF EXISTS cms_menu;
DROP TABLE IF EXISTS cms_pages;

SET FOREIGN_KEY_CHECKS=1;
